/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package textsummarization;

import beans.UserBean;
import java.awt.Container;
import java.awt.Toolkit;
import java.sql.Connection;
import services.ConnectionThread;
import services.UserActivityServices;

/**
 *
 * @author dell1
 */
public class MainFrame extends javax.swing.JFrame {
    

    /**
     * Creates new form MainFrame
     */
    static int id;
    static int aid;
    public MainFrame(UserBean objbean,int aid1) {
        setUndecorated(true);
        initComponents();
        
        setSize(Toolkit.getDefaultToolkit().getScreenSize());
        setResizable(false);
        c=this.getContentPane();
        id=objbean.getUserId();
        aid=aid1;
        if(objbean.getUserType().equalsIgnoreCase("user"))
        {
            mbMainFrame.remove(mnuReport);
            mnuMaintainance.remove(miManageUsers);
        }
        
        
    }

    public static Container c;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        mbMainFrame = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        miLogout = new javax.swing.JMenuItem();
        mnuMaintainance = new javax.swing.JMenu();
        miManageUsers = new javax.swing.JMenuItem();
        miManageProfile = new javax.swing.JMenuItem();
        mnuReport = new javax.swing.JMenu();
        miUserReports = new javax.swing.JMenuItem();
        mnuServer = new javax.swing.JMenu();
        miStartServer = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuFile.setText("File");

        miLogout.setText("Logout");
        miLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLogoutActionPerformed(evt);
            }
        });
        mnuFile.add(miLogout);

        mbMainFrame.add(mnuFile);

        mnuMaintainance.setText("Maintainance");

        miManageUsers.setText("Manage Users");
        miManageUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miManageUsersActionPerformed(evt);
            }
        });
        mnuMaintainance.add(miManageUsers);

        miManageProfile.setText("Manage Profile");
        miManageProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miManageProfileActionPerformed(evt);
            }
        });
        mnuMaintainance.add(miManageProfile);

        mbMainFrame.add(mnuMaintainance);

        mnuReport.setText("Report");

        miUserReports.setText("User Reports");
        miUserReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUserReportsActionPerformed(evt);
            }
        });
        mnuReport.add(miUserReports);

        mbMainFrame.add(mnuReport);

        mnuServer.setText("Server");

        miStartServer.setText("Start Server");
        miStartServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miStartServerActionPerformed(evt);
            }
        });
        mnuServer.add(miStartServer);

        mbMainFrame.add(mnuServer);

        setJMenuBar(mbMainFrame);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miManageProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miManageProfileActionPerformed
       
        c.removeAll();
        c.setVisible(false);
        ManageProfile objMP=new ManageProfile(id);
        objMP.setBounds(10, 10, 500, 600);
        c.add(objMP);
        c.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_miManageProfileActionPerformed

    private void miUserReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUserReportsActionPerformed
      
        UserReport ur=new UserReport();
        ur.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_miUserReportsActionPerformed

    private void miManageUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miManageUsersActionPerformed

        c.removeAll();
        c.setVisible(false);
        ManageUsers objMU=new ManageUsers();
        objMU.setBounds(10, 10, 500, 600);
        c.add(objMU);
        c.setVisible(true);
    
        // TODO add your handling code here:
    }//GEN-LAST:event_miManageUsersActionPerformed

    private void miLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLogoutActionPerformed

        UserActivityServices.insertLogoutTime(aid);
        
        LoginPage lp=new LoginPage();
        lp.setVisible(true);
        
        this.dispose();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_miLogoutActionPerformed

    private void miStartServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miStartServerActionPerformed

        ConnectionThread ct=new ConnectionThread();
        ct.start();
        
       
        // TODO add your handling code here:
    }//GEN-LAST:event_miStartServerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuBar mbMainFrame;
    private javax.swing.JMenuItem miLogout;
    private javax.swing.JMenuItem miManageProfile;
    private javax.swing.JMenuItem miManageUsers;
    private javax.swing.JMenuItem miStartServer;
    private javax.swing.JMenuItem miUserReports;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenu mnuMaintainance;
    private javax.swing.JMenu mnuReport;
    private javax.swing.JMenu mnuServer;
    // End of variables declaration//GEN-END:variables
}
